# Site settings
title: Genesis AI Solutions
email: contato@genesisaisolutions.com
description: "Soluções automatizadas e inteligentes para otimização, escalabilidade e sucesso do seu negócio."
baseurl: "" # Root
url: "https://leoslg.github.io/genesis"

# Redes sociais
instagram: https://www.instagram.com/genesissolutions.ai/
facebook: https://www.facebook.com/genesisaisolutions
linkedin: https://www.linkedin.com/company/solutionsgenesis/
whatsapp: https://api.whatsapp.com/send?phone=5566992453447

# Build settings
markdown: kramdown
